---
title: "Verifikation / Validation im med Labor"
author: "Oliver Speer"
date: "2024-01-25"
format: 
  revealjs:
    self_contained: true
    slide-number: true
    theme: white
    transition: slide
    logo: logo_pos.png
    css: style.css
editor: visual
jupyter: python3
---


## Was erwartet Euch in den kommenden 60 Minuten?

- Quiz
- Begriffsklärungen
- Warum Verifikationen und Validierungen?
- Welche Arten von Verifikationen und Validierungen gibt es?
- Regulatorische Grundlagen
- Verifikationen und Validierungen in der Klinischen Chemie
- Verifikationen und Validierungen in der Mikrobiologie
- Verifikationen und Validierungen in der Hämatologie
- Verifiaktionen und Validierungen in der IT
- Quiz

## Verifikationen und Validierungen im medizinischen Labor
### Begriffsdefinitionen

- Warum Verifikationen und Validierungen?
- Was ist eine Verifikation?
- Was ist eine Validierung?
- Was ist eine Verifizierung?
- Was ist eine Qualifizierung?
- Was ist eine Kalibrierung?
- Was ist eine Messunsicherheit?
- Was ist eine Messabweichung?
- Was ist eine Messgenauigkeit?
- Was ist eine Messpräzision?
- Was ist eine Messrichtigkeit?
- Was ist eine Messwiederholbarkeit?
- Was ist eine Messwert?
- Was ist eine Messwertverteilung?
- Was ist eine Messwertverteilungsfunktion?

##  Statistische Grundlagen

- Passings-Bablok-Regression
- Bland-Altman-Plot


## Praktische Beispiele

- Verifikationen und Validierungen in der Klinischen Chemie
  Siemens vs Beckman Coulter
  
## Praktische Beispiele
  
   Siemens vs Optilite
   

